// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqkxwxoursqvxowrgvlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxa3h3eG91cnNxdnhvd3Jndmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDA4MzEsImV4cCI6MjA2NjQxNjgzMX0.WcqDKxtPlrWBYrSITfdKFngKt1twKRFrkus9cl_Oh_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);